config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources :grading_levels
  map.resources :class_timings
  map.resources :subjects
  map.resources :attendances
  map.resources :employee_attendances
  map.resources :attendance_reports

  map.feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
  map.feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'
  map.resources :courses, :has_many => :batches

  map.resources :batches do |batch|
    batch.resources :exam_groups
    batch.resources :additional_exam_groups
    batch.resources :elective_groups, :as => :electives
  end

  map.resources :exam_groups do |exam_group|
    exam_group.resources :exams, :member => { :save_scores => :post }
  end

 map.resources :additional_exam_groups do |additional_exam_group|
    additional_exam_group.resources :additional_exams , :member => { :save_additional_scores => :post }
  end

  map.root :controller => 'user', :action => 'login'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id/:id2'
  map.connect ':controller/:action/:id.:format'

end

app/models/batch.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class Batch < ActiveRecord::Base
  belongs_to :course

  has_many :students
  has_many :archived_students
  has_many :grading_levels, :conditions => { :is_deleted => false }
  has_many :subjects, :conditions => { :is_deleted => false }
  has_many :exam_groups
  has_many :fee_category , :class_name => "FinanceFeeCategory"
  has_many :elective_groups
  has_many :additional_exam_groups

  has_and_belongs_to_many :graduated_students, :class_name => 'Student', :join_table => 'batch_students'

  delegate :course_name,:section_name, :code, :to => :course

  validates_presence_of :name, :start_date, :end_date

  named_scope :active, :conditions => { :is_deleted => false, :is_active => true }
  named_scope :deleted, :conditions => { :is_deleted => true }

  def validate
    errors.add(:start_date, 'should be before end date.') \
      if self.start_date > self.end_date \
      if self.start_date and self.end_date
  end

  def full_name
    "#{code} - #{name}"
  end

  def course_section_name
    "#{course_name} - #{section_name}"
  end
  
  def inactivate
    update_attribute(:is_deleted, true)
  end

  def grading_level_list
    levels = self.grading_levels
    levels.empty? ? GradingLevel.default : levels
  end

  def fee_collection_dates
    FinanceFeeCollection.find_all_by_batch_id(self.id,:conditions => "is_deleted = false")
  end

  def all_students
    Student.find_all_by_batch_id(self.id)
  end

  def normal_batch_subject
    Subject.find_all_by_batch_id(self.id,:conditions=>["elective_group_id IS NULL AND is_deleted = false"])
  end
  def elective_batch_subject(elect_group)
    Subject.find_all_by_batch_id_and_elective_group_id(self.id,elect_group,:conditions=>["elective_group_id IS NOT NULL AND is_deleted = false"])
  end
end

app/models/user.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class User < ActiveRecord::Base
  attr_accessor :password, :role, :old_password, :new_password, :confirm_password

  validates_uniqueness_of :username, :email
  validates_length_of     :username, :within => 1..20
  validates_length_of     :password, :within => 4..40, :allow_nil => true
  validates_format_of     :username, :with => /^[A-Z0-9_-]*$/i,
    :message => "must contain only letters, numbers, and underscores"
  validates_format_of     :email, :with => /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i,
    :message => "must be a valid email address"
  validates_presence_of   :role
  validates_presence_of   :email, :on=>:create
  validates_presence_of   :password, :on => :create
  
  has_and_belongs_to_many :privileges

  has_one :student_record,:class_name=>"Student",:foreign_key=>"user_id"
  has_one :employee_record,:class_name=>"Employee",:foreign_key=>"user_id"

  def before_save
    self.salt = random_string(8) if self.salt == nil
    self.hashed_password = Digest::SHA1.hexdigest(self.salt + self.password) unless self.password.nil?

    self.admin, self.student, self.employee = false, false, false

    self.admin    = true if self.role == 'Admin'
    self.student  = true if self.role == 'Student'
    self.employee = true if self.role == 'Employee'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def check_reminders
    reminders =[]
    reminders = Reminder.find(:all , :conditions => ["recipient = '#{self.id}'"])
    count = 0
    reminders.each do |r|
      unless r.is_read
        count += 1
      end
    end
    return count
  end

  def self.authenticate?(username, password)
    u = User.find_by_username username
    u.hashed_password == Digest::SHA1.hexdigest(u.salt + password)
  end

  def random_string(len)
    randstr = ""
    chars = ("0".."9").to_a + ("a".."z").to_a + ("A".."Z").to_a
    len.times { randstr << chars[rand(chars.size - 1)] }
    randstr
  end

  def role_name
    return "Admin" if self.admin?
    return "Student" if self.student?
    return "Employee" if self.employee?
    return nil
  end
  
  def role_symbols
    prv = []
    @privilge_symbols ||= privileges.map { |privilege| prv << privilege.name.underscore.to_sym }
   
    if admin?
      return [:admin] + prv
    elsif student?
      return [:student] + prv
    elsif employee?
      return [:employee] + prv
    else
      return prv
    end
  end
  
end

app/controllers/user_controller.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class UserController < ApplicationController
    layout :choose_layout
    before_filter :login_required, :except => [:forgot_password, :login, :set_new_password, :reset_password]
    before_filter :only_admin_allowed, :only => [:edit, :create, :index, :edit_privilege, :user_change_password]
    before_filter :protect_user_data, :only => [:profile, :user_change_password]
    #  filter_access_to :edit_privilege
    def choose_layout
        return 'login' if action_name == 'login' or action_name == 'set_new_password'
        return 'forgotpw' if action_name == 'forgot_password'
        return 'dashboard' if action_name == 'dashboard'
        'application'
    end
  
    def all
        @users = User.all
    end
  
    def list_user
        if params[:user_type] == 'Admin'
            @users = User.find(:all, :conditions => {:admin => true}, :order => 'first_name ASC')
            render(:update) do |page|
                page.replace_html 'users', :partial=> 'users'
                page.replace_html 'employee_user', :text => ''
                page.replace_html 'student_user', :text => ''
            end
        elsif params[:user_type] == 'Employee'
            render(:update) do |page|
                hr = Configuration.find_by_config_value("HR")
                unless hr.nil?
                    page.replace_html 'employee_user', :partial=> 'employee_user'
                    page.replace_html 'users', :text => ''
                    page.replace_html 'student_user', :text => ''
                else
                    @users = User.find_all_by_employee(1)
                    page.replace_html 'users', :partial=> 'users'
                    page.replace_html 'employee_user', :text => ''
                    page.replace_html 'student_user', :text => ''
                end
            end
        elsif params[:user_type] == 'Student'
            render(:update) do |page|
                page.replace_html 'student_user', :partial=> 'student_user'
                page.replace_html 'users', :text => ''
                page.replace_html 'employee_user', :text => ''
            end
        elsif params[:user_type] == ''
            @users = ""
            render(:update) do |page|
                page.replace_html 'users', :partial=> 'users'
                page.replace_html 'employee_user', :text => ''
                page.replace_html 'student_user', :text => ''
            end
        end
    end

    def list_employee_user
        emp_dept = params[:dept_id]
        @employee = Employee.find_all_by_employee_department_id(emp_dept, :order =>'first_name ASC')
        @users = @employee.collect { |employee| employee.user}
        @users.delete(nil)
        render(:update) {|page| page.replace_html 'users', :partial=> 'users'}
    end

    def list_student_user
        batch = params[:batch_id]
        @student = Student.find_all_by_batch_id(batch, :conditions => { :is_active => true },:order =>'first_name ASC')
        @users = @student.collect { |student| student.user}
        @users.delete(nil)
        render(:update) {|page| page.replace_html 'users', :partial=> 'users'}
    end

    def change_password
    
        if request.post?
            @user = current_user
            if User.authenticate?(@user.username, params[:user][:old_password])
                if params[:user][:new_password] == params[:user][:confirm_password]
                    @user.password = params[:user][:new_password]
                    @user.update_attributes(:password => @user.password,
                        :role => @user.role_name
                    )
                    flash[:notice] = 'Password changed successfully.'
                    redirect_to :action => 'dashboard'
                else
                    flash[:warn_notice] = '<p>Password confirmation failed. Please try again.</p>'
                end
            else
                flash[:warn_notice] = '<p>The old password you entered is incorrect. Please enter valid password.</p>'
            end
        end
    end

    def user_change_password
        user = User.find_by_username(params[:id])

        if request.post?
            if params[:user][:new_password]=='' and params[:user][:confirm_password]==''
                flash[:warn_notice]= "<p>Password fields cannot be blank!</p>"
            else
                if params[:user][:new_password] == params[:user][:confirm_password]
                    user.password = params[:user][:new_password]
                    user.update_attributes(:password => user.password,
                        :role => user.role_name
                    )
                    flash[:notice]= "Password has been updated successfully!"
                    redirect_to :action=>"edit", :id=>user.username
                else
                    flash[:warn_notice] = '<p>Password confirmation failed. Please try again.</p>'
                end
            end

      
        end
    end

    def user_change_role
        user = User.find_by_username(params[:id])

        if request.post?
				user.update_attributes(params[:user])
				flash[:notice]="Role has been changed successfully!"
				redirect_to :action=>"profile", :id=>user.username
        end
    end

    def create
        @config = Configuration.available_modules

        @user = User.new(params[:user])
        if request.post?
      
            if @config.include?('HR')
                @employee = Employee.new

                @employee.first_name =  @user.first_name
                @employee.last_name =  @user.last_name
                @employee.employee_number =  @user.username

                @employee.employee_category_id =  1
                @employee.employee_position_id =  1
                @employee.employee_department_id =  1
                @employee.employee_grade_id =  1
                @employee.date_of_birth =  Date.today - 20.year
                @employee.joining_date =  Date.today - 5.year
                if @employee.save or @user.save
                    flash[:notice] = 'User account created!'
                    redirect_to :controller => 'user', :action => 'edit', :id => @user.username
                else
                    flash[:notice] = 'User account not created!'
                end
            end
        end
    end

    def delete
        @user = User.find_by_username(params[:id]).destroy
        flash[:notice] = 'User account deleted!'
        redirect_to :controller => 'user'
    end

    def dashboard
        @user = current_user
        @config = Configuration.available_modules
        @employee = @user.employee_record if ['employee','admin'].include?(@user.role_name.downcase)
        @student = @user.student_record  if @user.role_name.downcase == 'student'
        @dash_news = News.find(:all, :limit => 5)
    end

    def edit
        @user = User.find_by_username(params[:id])
        @current_user = current_user
        if request.post? and @user.update_attributes(params[:user])
            flash[:notice] = 'User account updated!'
            redirect_to :controller => 'user', :action => 'profile', :id => @user.username
        end
    end

    def forgot_password
        #    flash[:notice]="You do not have permission to access forgot password!"
        #    redirect_to :action=>"login"
        @network_state = Configuration.find_by_config_key("NetworkState")
        if request.post? and params[:reset_password]
            if user = User.find_by_email(params[:reset_password][:email])
                user.reset_password_code = Digest::SHA1.hexdigest( "#{user.email}#{Time.now.to_s.split(//).sort_by {rand}.join}" )
                user.reset_password_code_until = 1.day.from_now
                user.role = user.role_name
                user.save(false)
                UserNotifier.deliver_forgot_password(user)
                flash[:notice] = "Reset Password link emailed to #{user.email}"
                redirect_to :action => "index"
            else
                flash[:notice] = "No user exists with email address #{params[:reset_password][:email]}"
            end
        end
    end

    def login
        @institute = Configuration.find_by_config_key("LogoName")
        if request.post? and params[:user]
            @user = User.new(params[:user])
            user = User.find_by_username @user.username
			if user and User.authenticate?(@user.username, @user.password)
                session[:user_id] = user.id
                flash[:notice] = "Welcome, #{user.first_name} #{user.last_name}!"
                redirect_to :controller => 'user', :action => 'dashboard'
            else
                flash[:notice] = 'Invalid username or password combination'
            end
        end
    end

    def logout
        session[:user_id] = nil
        flash[:notice] = 'Logged out'
        redirect_to :controller => 'user', :action => 'login'
    end

    def profile
        @config = Configuration.available_modules
        @current_user = current_user
        @username = @current_user.username if session[:user_id]
        @user = User.find_by_username(params[:id])
        unless @user.nil?
            @employee = Employee.find_by_employee_number(@user.username)
            @student = Student.find_by_admission_no(@user.username)
        else

app/views/user/_employee_user.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

 <div class="label-field-pair">

<div class="text-input-bg"><%= select :user_type, :type, EmployeeDepartment.active.map {|c| [c.name, c.id]},
    {:prompt => 'Select a Department '},
    {:onChange => "#{remote_function(:url => {:action => "list_employee_user"},
    :with => "'dept_id='+value",
        :before => "Element.show('loader')",
        :success => "Element.hide('loader')"
        )}"} %>

</div>
 </div>

app/views/user/dashboard.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content_header">
  <h1 id="main_heading">Welcome</h1>
  <h3 id="sub_heading">to <%= @user.username %> dashboard</h3>
</div>

<% unless flash[:notice].nil? %> <p class="flash-msg"> <%= flash[:notice] %> </p> <% end %>

<div id="user_options">

  <% if @user.admin? %>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Admission</p></div>', {:controller => "student", :action => "admission1"},
        :class => "option_buttons", :id => "admission_button", :title => "Enter a Students admission details into the school records"%>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Student Details</p></div>', {:controller => "student", :action => "index"},
        :class => "option_buttons", :id => "student_details_button", :title => "Search for an existing and former student records"%>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Manage Users</p></div>', {:controller => "user", :action => "index"},
        :class => "option_buttons", :id => "manage_users_button", :title => "     Manage the Users of Adequate Web Solutions" %>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Manage News</p></div>', {:controller => "news", :action => "index"},
        :class => "option_buttons", :id => "manage_news_button",:title => "View or publish latest school news and announcements"%>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Examinations</p></div>', {:controller => "exam", :action => "index"},
        :class => "option_buttons", :id => "examinations_button",:title => "See examination details and results" %>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Timetable</p></div>', {:controller => "timetable", :action => "index"},
        :class => "option_buttons", :id => "timetable_button",:title => "    Timetable management module" %>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Attendance</p></div>', {:controller => "student_attendance", :action => "index"},
        :class => "option_buttons", :id => "student_attendance_button", :title => "Manage the attendance for the students" %>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Settings</p></div>', {:controller => "configuration", :action => "index"},
        :class => "option_buttons", :id => "settings_button", :title => "Configure the basic school settings" %>
    </div>

    <% if @config.include?('HR') %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Human Resources</p></div>', {:controller => "employee", :action => "hr"},
          :class => "option_buttons", :id => "hr_button", :title => "        Human Resource Department" %>
      </div>

    <% end %>

    <% if @config.include?('Finance') %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Finance</p></div>', {:controller => "finance", :action => "index"},
          :class => "option_buttons", :id => "finance_button", :title => "        Manages Finance module    " %>
      </div>
    <% end %>

  <% elsif @user.student? %>

    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>My Profile</p></div>', {:controller => "student", :action => "profile", :id => @student.id},
        :class => "option_buttons", :id => "student_details_button", :title => "           View your profile" %>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Campus News</p></div>', {:controller => "news", :action => "index"},
        :class => "option_buttons", :id => "campus_news_button",:title => "    Search for news/announcements"%>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Timetable</p></div>', {:controller => "timetable", :action => "student_view",:id=>@student.id},
        :class => "option_buttons", :id => "timetable_button",:title => "   Timetable management module" %>
    </div>
    <div class="button-box">
      <% unless @user.check_reminders == 0 %>
        <div class="reminder1">
          <%= link_to '<div class ="button-label"><p>Reminders</p></div>', {:controller => "reminder", :action => "index"},
            :class => "option_buttons", :id => "reminders_button", :title => "             Student messages"%>
          <div class ="count"><%= render :partial => 'layouts/reminder_count' %></div>
        </div>
      <% else %>
        <%= link_to '<div class ="button-label"><p>Reminders</p></div>', {:controller => "reminder", :action => "index"},
          :class => "option_buttons", :id => "reminders_button", :title => "             Student messages"%>
      <% end %>
    </div>
    <div class="button-box">
      <%= link_to '<div class ="button-label"><p>Academics</p></div>', {:controller => "student", :action => "reports",:id => @student.id},
        :class => "option_buttons", :id => "academic_button",:title => "           Academic Reports   " %>
    </div>
  <% else %>

    <% if @config.include?('HR') %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>My Profile</p></div>', {:controller => "employee", :action => "profile",:id => @employee.id},
          :class => "option_buttons", :id => "my_profile_button", :title => "      View your profile       " unless @employee.nil?%>
      </div>
    <% end  %>


    <% if permitted_to? :admission1, :student %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Admission</p></div>', {:controller => "student", :action => "admission1"},
          :class => "option_buttons", :id => "admission_button", :title => "Enter a Students admission details into the school records"%>
      </div>
    <%end%>

    <% if permitted_to? :index, :student%>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Student Details</p></div>', {:controller => "student", :action => "index"},
          :class => "option_buttons", :id => "student_details_button", :title => "Search for an existing and former student records"%>
      </div>
    <%end%>

    <% if permitted_to? :index, :user %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Manage Users</p></div>', {:controller => "user", :action => "index"},
          :class => "option_buttons", :id => "manage_users_button", :title => "Manage the Users of Fedena" %>
      </div>
    <%end%>

    <% if permitted_to? :add,:news %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Manage News</p></div>', {:controller => "news", :action => "index"},
          :class => "option_buttons", :id => "manage_news_button",:title => "Search for news/announcements"%>
      </div>
    <% else %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Campus News</p></div>', {:controller => "news", :action => "index"},
          :class => "option_buttons", :id => "campus_news_button",:title => "   Search for news/announcements"%>
      </div>
    <%end%>

    <% if permitted_to? :leave_management, :employee %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Leave</p></div>', {:controller => "employee", :action => "leave_management"},
          :class => "option_buttons", :id => "leaves_button", :title => "  Leave Management"%>
      </div>
    <%else%>
      <% if @config.include?('HR') %>
        <div class="button-box">
          <%= link_to "<div class ='button-label'><p>Leave</p></div>", {:controller => "employee_attendance", :action => "leaves",:id => @employee.id},
            :class => "option_buttons", :id => "leaves_button", :title => "Employee leave details." unless @employee.nil?%>
          
        </div>
      <%end%>
    <%end%>

    <div class="button-box">
      <% unless @user.check_reminders == 0 %>
        <div class="reminder1">
          <%= link_to '<div class ="button-label"><p>Reminders</p></div>', {:controller => "reminder", :action => "index"},
            :class => "option_buttons", :id => "reminders_button", :title => "             Employee messages"%>
          <div class ="count"><%= render :partial => 'layouts/reminder_count' %></div>
        </div>

      <% else %>
        <div class="button-box">
          <%= link_to '<div class ="button-label"><p>Reminders</p></div>', {:controller => "reminder", :action => "index"},
            :class => "option_buttons", :id => "reminders_button", :title => "             Student messages"%>
        </div>
      <% end %>
    </div>

    <% if @user.employee? %>
      <% @employee_subjects= @user.employee_record.subject_ids  %>
      <% if @employee_subjects.empty?%>

        <% if permitted_to? :index, :student_attendance or  permitted_to? :index, :attendances %>
          <div class="button-box">
            <%= link_to '<div class ="button-label"><p>Attendance</p></div>', {:controller => "student_attendance", :action => "index"},
              :class => "option_buttons", :id => "student_attendance_button", :title => "Manage the attendance for the students" %>
          </div>
        <%end%>

        <% if permitted_to? :index, :exam and (@user.privileges.map{|p| p.id}.include?(1) or @user.privileges.map{|p| p.id}.include?(2) or @user.privileges.map{|p| p.id}.include?(3)) %>
          <div class="button-box">
            <%= link_to '<div class ="button-label"><p>Examinations</p></div>', {:controller => "exam", :action => "index"},
              :class => "option_buttons", :id => "examinations_button",:title => "See examination details and results" %>
          </div>
        <% end %>
      <% else %>
        <% @attendance_type = Configuration.find_by_config_key('StudentAttendanceType') %>
        <% unless @attendance_type.config_value == 'Daily' %>
          <div class="button-box">
            <%= link_to '<div class ="button-label"><p>Attendance</p></div>', {:controller => "student_attendance", :action => "index"},
              :class => "option_buttons", :id => "student_attendance_button", :title => "Manage the attendance for the students" %>
          </div>
        <% else %>
          <div class="button-box">
            <% if permitted_to? :index, :student_attendance or  permitted_to? :index, :attendances %>
              <%= link_to '<div class ="button-label"><p>Attendance</p></div>', {:controller => "student_attendance", :action => "index"},
                :class => "option_buttons", :id => "student_attendance_button", :title => "Manage the attendance for the students" %>
            <%end%>
          </div>
        <% end %>
        <div class="button-box">
          <%= link_to '<div class ="button-label"><p>Examinations</p></div>', {:controller => "exam", :action => "index"},
            :class => "option_buttons", :id => "examinations_button",:title => "See examination details and results" %>
        </div>
      <% end  %>
    <% end %>

    <% if permitted_to? :index, :timetable %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Timetable</p></div>', {:controller => "timetable", :action => "index"},
          :class => "option_buttons", :id => "timetable_button",:title => "Timetable management module" %>
      </div>
    <%end%>

    <% if permitted_to? :index, :configuration %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Settings</p></div>', {:controller => "configuration", :action => "index"},
          :class => "option_buttons", :id => "settings_button", :title => "Configure the basic school settings" %>
      </div>
    <% end %>
    <% if @config.include?('HR') %>
      <% if permitted_to? :hr,:employee %>
        <div class="button-box">
          <%= link_to '<div class ="button-label"><p>Human Resources</p></div>', {:controller => "employee", :action => "hr"},
            :class => "option_buttons", :id => "hr_button", :title => "        Human Resource Department" %>
        </div>
      <% end %>
    <% end %>

    <% if permitted_to? :index,:finance %>
      <div class="button-box">
        <%= link_to '<div class ="button-label"><p>Finance</p></div>', {:controller => "finance", :action => "index"},
          :class => "option_buttons", :id => "finance_button", :title => "        Manages Finance module    " %>
      </div>
    <% end %>

  <% end %>


</div>

<div id="option_description"> </div>